FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
ARG VITE_APP_BASE_URL=http://localhost:6000/v1
ARG VITE_APP_SOCKET_URL=http://localhost:6000
ARG VITE_APP_GOOGLE_CLINT_ID=""
ENV VITE_APP_BASE_URL=$VITE_APP_BASE_URL
ENV VITE_APP_SOCKET_URL=$VITE_APP_SOCKET_URL
ENV VITE_APP_GOOGLE_CLINT_ID=$VITE_APP_GOOGLE_CLINT_ID
RUN ./node_modules/.bin/vite build
FROM nginx:1.25-alpine
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]